#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
CC := /home/wago/wago/ptxproj/selected_toolchain/arm-linux-gnueabihf-gcc
CXX := /home/wago/wago/ptxproj/selected_toolchain/arm-linux-gnueabihf-g++
LD := $(CXX)
AR := ar
OBJCOPY := objcopy

#Additional flags
PREPROCESSOR_MACROS := DEBUG=1
INCLUDE_DIRS := /home/wago/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/include /home/wago/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include/OsLinux /home/wago/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include /home/wago/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include/dal
LIBRARY_DIRS := /home/wago/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib /home/wago/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/lib
LIBRARY_NAMES := dal glib-2.0 ffi pthread rt libloader oslinux dl ncurses pcre config gmodule-2.0 z gio-2.0 dbus-glib-1 wago_dbus dbus-1 gobject-2.0 dbuskbuscommon crypto ssl mosquitto oms json-c
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -std=c99 -ggdb -ffunction-sections -O0
CXXFLAGS := -ggdb -ffunction-sections -O0
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 
LINKER_SCRIPT := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
IS_LINUX_PROJECT := 1
